//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringCompare.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>I am John.</string>\r\n  <string>I am a student of St. Andrew’s High School." +
            "</string>\r\n  <string>I am working in Microsoft Corporation.</string>\r\n  <string>" +
            "I am doing business.</string>\r\n  <string>I am looking for a job.</string>\r\n  <st" +
            "ring>I am a housewife.</string>\r\n  <string>He is my father.</string>\r\n  <string>" +
            "She is my mother.</string>\r\n  <string>He is my elder brother.</string>\r\n  <strin" +
            "g>This is my younger brother.</string>\r\n  <string>She is my elder sister.</strin" +
            "g>\r\n  <string>She is my younger sister.</string>\r\n  <string>He is my grandfather" +
            ".</string>\r\n  <string>She is my grandmother.</string>\r\n  <string>He is my neighb" +
            "our.</string>\r\n  <string>He is my classmate.</string>\r\n  <string>He is my collea" +
            "gue. </string>\r\n  <string>How are you?</string>\r\n  <string>How is life?</string>" +
            "\r\n  <string>How are things?</string>\r\n  <string>How is your married life?</strin" +
            "g>\r\n  <string>Fine.</string>\r\n  <string>I am fine.</string>\r\n  <string>Pretty we" +
            "ll.</string>\r\n  <string>Fantastic.</string>\r\n  <string>Fit as a fiddle.</string>" +
            "\r\n  <string>I am fine.</string>\r\n  <string>What about you?</string>\r\n  <string>F" +
            "ine.</string>\r\n  <string>How about you?</string>\r\n  <string>I am fine and you?</" +
            "string>\r\n  <string>How is your father?</string>\r\n  <string>How is your mother?</" +
            "string>\r\n  <string>How is your brother?</string>\r\n  <string>How is your sister?<" +
            "/string>\r\n  <string>He is fine.</string>\r\n  <string>Oh, well.</string>\r\n  <strin" +
            "g>He is doing fine.</string>\r\n  <string>How is everybody?</string>\r\n  <string>Ho" +
            "w is everybody at home?</string>\r\n  <string>Everybody is fine.</string>\r\n  <stri" +
            "ng>All are fine. </string>\r\n  <string>May I know your name?</string>\r\n  <string>" +
            "Your name please?</string>\r\n  <string>Your good name please?</string>\r\n  <string" +
            ">What\'s your name?</string>\r\n  <string>I am Mary.</string>\r\n  <string>I am Miss." +
            " Catherine.</string>\r\n  <string>I am Mrs. Obama.</string>\r\n  <string>What are yo" +
            "u?</string>\r\n  <string>What do you do?</string>\r\n  <string>Where do you work?</s" +
            "tring>\r\n  <string>Where are you working?</string>\r\n  <string>I am working in Goo" +
            "gle.</string>\r\n  <string>I am working as a Advertising Agent.</string>\r\n  <strin" +
            "g>What is your father?</string>\r\n  <string>What is he?</string>\r\n  <string>Where" +
            " does he work?</string>\r\n  <string>He is working in MSN – USA.</string>\r\n  <stri" +
            "ng>He is working as a software engineer in WIPRO.</string>\r\n  <string>He is a so" +
            "ftware engineer in WIPRO. </string>\r\n  <string>Where do you live?</string>\r\n  <s" +
            "tring>Where are you living?</string>\r\n  <string>Where is your residence?</string" +
            ">\r\n  <string>I live in London.</string>\r\n  <string>I am living in London.</strin" +
            "g>\r\n  <string>I am residing at London.</string>\r\n  <string>Where are you from?</" +
            "string>\r\n  <string>Where do you come from?</string>\r\n  <string>Which is your nat" +
            "ive town?</string>\r\n  <string>You belong to which place?</string>\r\n  <string>I a" +
            "m from Chicago.</string>\r\n  <string>I come from Chicago.</string>\r\n  <string>My " +
            "native town is Chicago.</string>\r\n  <string>I belong to Chicago.</string>\r\n  <st" +
            "ring>Where does he live?</string>\r\n  <string>Where do they live?</string>\r\n  <st" +
            "ring>He lives at Paris in France.</string>\r\n  <string>They live in at Paris in F" +
            "rance. </string>\r\n  <string>What is your educational qualification?</string>\r\n  " +
            "<string>What is your qualification?</string>\r\n  <string>How far have you studied" +
            "?</string>\r\n  <string>I am an Engineer.</string>\r\n  <string>I have done my B.S. " +
            "of Engineering.</string>\r\n  <string>I am a graduate in Engineering.</string>\r\n  " +
            "<string>I am a post graduate in Medicine.</string>\r\n  <string>I have completed m" +
            "y M.S.</string>\r\n  <string>I have studied unto Graduation.</string>\r\n  <string>I" +
            " had my school education in London.</string>\r\n  <string>I had my schooling in Lo" +
            "ndon.</string>\r\n  <string>I did my college studies in Washington. </string>\r\n  <" +
            "string>Could you tell us something about your family?</string>\r\n  <string>Ours i" +
            "s a large family.</string>\r\n  <string>Ours is a small family.</string>\r\n  <strin" +
            "g>Ours is a large joint family.</string>\r\n  <string>Ours is an orthodox family.<" +
            "/string>\r\n  <string>Ours is a modern, liberal family.</string>\r\n  <string>There " +
            "are eight members in our family.</string>\r\n  <string>There are four members in o" +
            "ur family.</string>\r\n  <string>We are six people at home. My father, my mother, " +
            "my two sisters and a brother besides myself.</string>\r\n  <string>I have two brot" +
            "hers and a sister.</string>\r\n  <string>We are two brothers and a sister at home." +
            "</string>\r\n  <string>I have three brothers and two sisters. </string>\r\n  <string" +
            ">What type of person are you?</string>\r\n  <string>I am frank.</string>\r\n  <strin" +
            "g>I am bold.</string>\r\n  <string>I am rather shy.</string>\r\n  <string>I am frien" +
            "dly.</string>\r\n  <string>I am reserved by nature.</string>\r\n  <string>I am very " +
            "strict.</string>\r\n  <string>I am outspoken.</string>\r\n  <string>I am always posi" +
            "tive.</string>\r\n  <string>My father is very honest.</string>\r\n  <string>My broth" +
            "er is very adamant.</string>\r\n  <string>My sister is very innocent.</string>\r\n  " +
            "<string>My mother is very affectionate.</string>\r\n  <string>My friend is very re" +
            "liable.</string>\r\n  <string>You belong to which place?</string>\r\n  <string>Which" +
            " is your home town?</string>\r\n  <string>I belong to New York.</string>\r\n  <strin" +
            "g>I am a native of Washington.</string>\r\n  <string>How far is it from Chennai?</" +
            "string>\r\n  <string>It is about 300 kms from Chennai.</string>\r\n  <string>How man" +
            "y hours drive?</string>\r\n  <string>It\'s about 8 hour journey by road.</string>\r\n" +
            "  <string>About 8 hours journey by road.</string>\r\n  <string>How is the weather " +
            "like?</string>\r\n  <string>The weather is hot.</string>\r\n  <string>The weather is" +
            " rather hot.</string>\r\n  <string>What is the major occupation of the people?</st" +
            "ring>\r\n  <string>What do the people do there?</string>\r\n  <string>The major occu" +
            "pation of the people is agriculture.</string>\r\n  <string>What language is spoken" +
            " there?</string>\r\n  <string>What language do they speak there?</string>\r\n  <stri" +
            "ng>They speak Tamil.</string>\r\n  <string>People speak Tamil.</string>\r\n  <string" +
            ">Tamil is spoken there.</string>\r\n  <string>How is the new house?</string>\r\n  <s" +
            "tring>The new house is very convenient.</string>\r\n  <string>The house is spaciou" +
            "s.</string>\r\n  <string>The house is commodious.</string>\r\n  <string>The house is" +
            " roomy.</string>\r\n  <string>The house is big.</string>\r\n  <string>The house is b" +
            "eautiful.</string>\r\n  <string>The house is lovely.</string>\r\n  <string>When are " +
            "you moving to the new house?</string>\r\n  <string>Are you letting out your house?" +
            "</string>\r\n  <string>How about water?</string>\r\n  <string>There is no water prob" +
            "lem at all.</string>\r\n  <string>There is plenty of water.</string>\r\n  <string>Th" +
            "ere is scarcity of water.</string>\r\n  <string>There is a well but the water is b" +
            "rackish.</string>\r\n  <string>The water is hard.</string>\r\n  <string>The water is" +
            " soft.</string>\r\n  <string>I feel happy.</string>\r\n  <string>I feel shy.</string" +
            ">\r\n  <string>I feel hungry.</string>\r\n  <string>I feel thirsty.</string>\r\n  <str" +
            "ing>I feel sleepy.</string>\r\n  <string>I feel tired.</string>\r\n  <string>I feel " +
            "giddy.</string>\r\n  <string>I feel guilty.</string>\r\n  <string>I feel feverish.</" +
            "string>\r\n  <string>I feel powerful.</string>\r\n  <string>I don\'t feel like eating" +
            " anything.</string>\r\n  <string>I don\'t feel like talking to anybody.</string>\r\n " +
            " <string>I don\'t feel like going out.</string>\r\n  <string>I don’t\' feel like wat" +
            "ching T.V.</string>\r\n  <string>I don\'t feel like walking fast.</string>\r\n  <stri" +
            "ng>What is your name?</string>\r\n  <string>My name is Raja.</string>\r\n  <string>W" +
            "hat are you?</string>\r\n  <string>I am a professor of English in University of Wi" +
            "sconsin.</string>\r\n  <string>What is your father?</string>\r\n  <string>He is a Bu" +
            "siness Man.</string>\r\n  <string>Where do you live?</string>\r\n  <string>We are li" +
            "ving in Wisconsin.</string>\r\n  <string>You belong to which place?</string>\r\n  <s" +
            "tring>I belong to Chennai.</string>\r\n  <string>How far is it from Mumbai?</strin" +
            "g>\r\n  <string>Chennai is 2000km from Mumbai.</string>\r\n  <string>How is the weat" +
            "her like?</string>\r\n  <string>It is always sunny there.</string>\r\n  <string>What" +
            " is the major occupation of the people there?</string>\r\n  <string>Agriculture is" +
            " the major occupation of the people there in.</string>\r\n  <string>What language " +
            "is spoken there?</string>\r\n  <string>Tamil is spoken there.</string>\r\n  <string>" +
            "What is your educational qualification?</string>\r\n  <string>I am a B.E. graduate" +
            ".</string>\r\n  <string>Where did you have your school education?</string>\r\n  <str" +
            "ing>I did my school education in Chicago.</string>\r\n  <string>Could you tell me " +
            "something about your family?</string>\r\n  <string>Ours is a joint family.</string" +
            ">\r\n  <string>We are six persons.</string>\r\n  <string>My father, my mother, my gr" +
            "and father, my grand mother, my sister and myself.</string>\r\n  <string>What type" +
            " of person are you?</string>\r\n  <string>I am friendly person.</string>\r\n  <strin" +
            "g>Very good.</string>\r\n  <string>Attend to the phone.</string>\r\n  <string>Arrang" +
            "e the books in order.</string>\r\n  <string>Bolt the door.</string>\r\n  <string>Bri" +
            "ng them here.</string>\r\n  <string>Bear in mind.</string>\r\n  <string>Call them in" +
            ".</string>\r\n  <string>Okay, come to the point.</string>\r\n  <string>Do the home w" +
            "ork.</string>\r\n  <string>Eat slowly.</string>\r\n  <string>Forget the past.</strin" +
            "g>\r\n  <string>Give it to them.</string>\r\n  <string>Hide it up somewhere.</string" +
            ">\r\n  <string>Keep your word.</string>\r\n  <string>Listen to me.</string>\r\n  <stri" +
            "ng>Lock the door.</string>\r\n  <string>Mind your tongue.</string>\r\n  <string>Mind" +
            " your business.</string>\r\n  <string>Mind the steps.</string>\r\n  <string>Make a n" +
            "ote of it.</string>\r\n  <string>Meet me tomorrow.</string>\r\n  <string>Get up.</st" +
            "ring>\r\n  <string>Wake him up.</string>\r\n  <string>Get dressed quickly.</string>\r" +
            "\n  <string>Switch off the T.V.</string>\r\n  <string>Keep the change.</string>\r\n  " +
            "<string>Remind me.</string>\r\n  <string>Return it safely.</string>\r\n  <string>Red" +
            "uce the volume.</string>\r\n  <string>Remember the date.</string>\r\n  <string>Put o" +
            "n your shirt.</string>\r\n  <string>Send him out.</string>\r\n  <string>Meet them in" +
            " person.</string>\r\n  <string>Note the address.</string>\r\n  <string>Pay the bill." +
            "</string>\r\n  <string>Show him around the city.</string>\r\n  <string>Throw it out." +
            "</string>\r\n  <string>Take them with you.</string>\r\n  <string>Take these tablets " +
            "for three days.</string>\r\n  <string>Read them aloud.</string>\r\n  <string>Don\'t d" +
            "isturb me.</string>\r\n  <string>Don\'t talk about that.</string>\r\n  <string>Don\'t " +
            "waste my time.</string>\r\n  <string>Don\'t go there.</string>\r\n  <string>Don\'t mov" +
            "e with them.</string>\r\n  <string>Don\'t ask me anything.</string>\r\n  <string>Don\'" +
            "t talk to me.</string>\r\n  <string>Don\'t cry.</string>\r\n  <string>Don\'t shout.</s" +
            "tring>\r\n  <string>Don\'t make noise.</string>\r\n  <string>Don\'t quarrel with him.<" +
            "/string>\r\n  <string>Don\'t eat too much.</string>\r\n  <string>Don\'t beat about the" +
            " bush.</string>\r\n  <string>Don\'t move.</string>\r\n  <string>Don\'t make me angry.<" +
            "/string>\r\n  <string>Don\'t beat him.</string>\r\n  <string>Don\'t tell lies.</string" +
            ">\r\n  <string>Don\'t rush me.</string>\r\n  <string>Don\'t confuse me.</string>\r\n  <s" +
            "tring>Don\'t get angry.</string>\r\n  <string>Don\'t keep the door open.</string>\r\n " +
            " <string>Don\'t spend all the money.</string>\r\n  <string>Don\'t think that you are" +
            " clever. </string>\r\n  <string>Is he your relative?</string>\r\n  <string>Is it Wel" +
            "come group of companies?</string>\r\n  <string>Is it number 17?</string>\r\n  <strin" +
            "g>Is the seat vacant?</string>\r\n  <string>Is it your first visit to Chennai?</st" +
            "ring>\r\n  <string>Is the shop open?</string>\r\n  <string>Is he at home?</string>\r\n" +
            "  <string>Is it true?</string>\r\n  <string>Is there anybody inside?</string>\r\n  <" +
            "string>Is she your sister?</string>\r\n  <string>Is your wife employed?</string>\r\n" +
            "  <string>Is it Jolarpet?</string>\r\n  <string>Is it 8-3 coach?</string>\r\n  <stri" +
            "ng>Is your friend in London?</string>\r\n  <string>Is he a teacher?</string>\r\n  <s" +
            "tring>Is it useful?</string>\r\n  <string>Are you ready?</string>\r\n  <string>Are y" +
            "ou free now?</string>\r\n  <string>Are you Mr. Murthy?</string>\r\n  <string>Are you" +
            " angry with me?</string>\r\n  <string>Are you afraid of them?</string>\r\n  <string>" +
            "Are you tired?</string>\r\n  <string>Are you married?</string>\r\n  <string>Are you " +
            "employed?</string>\r\n  <string>Are you interested in that?</string>\r\n  <string>Ar" +
            "e you awake?</string>\r\n  <string>Are you aware of that?</string>\r\n  <string>Are " +
            "you a relative of Mr. Mohan?</string>\r\n  <string>Are you not well?</string>\r\n  <" +
            "string>Are they your relatives?</string>\r\n  <string>Are they from abroad?</strin" +
            "g>\r\n  <string>Are the shops open?</string>\r\n  <string>Are you satisfied now?</st" +
            "ring>\r\n  <string>Are you joking?</string>\r\n  <string>What is your aim in life?</" +
            "string>\r\n  <string>What is your hobby?</string>\r\n  <string>What day is today?</s" +
            "tring>\r\n  <string>What date is today?</string>\r\n  <string>What station is it?</s" +
            "tring>\r\n  <string>What is your sister\'s name?</string>\r\n  <string>What is his na" +
            "me?</string>\r\n  <string>What is your opinion?</string>\r\n  <string>What are you?<" +
            "/string>\r\n  <string>What is the name of that girl?</string>\r\n  <string>What do y" +
            "ou think of him?</string>\r\n  <string>What do you do on Sundays?</string>\r\n  <str" +
            "ing>What do you want?</string>\r\n  <string>What did you say?</string>\r\n  <string>" +
            "What did he ask you?</string>\r\n  <string>What did you buy?</string>\r\n  <string>W" +
            "hat do you do?</string>\r\n  <string>What did you do?</string>\r\n  <string>What wil" +
            "l you do?</string>\r\n  <string>What are you doing?</string>\r\n  <string>What have " +
            "you decided?</string>\r\n  <string>Where are you coming from?</string>\r\n  <string>" +
            "Where are you now?</string>\r\n  <string>Where are my books?</string>\r\n  <string>W" +
            "here do you live?</string>\r\n  <string>Where did you meet him?</string>\r\n  <strin" +
            "g>Where have you kept the book?</string>\r\n  <string>Where is he working now?</st" +
            "ring>\r\n  <string>Where are you buying the vegetables?</string>\r\n  <string>Where " +
            "do you buy the vegetables?</string>\r\n  <string>Where is your brother now?</strin" +
            "g>\r\n  <string>When is your birthday?</string>\r\n  <string>When is the next train?" +
            "</string>\r\n  <string>When are you going to Delhi?</string>\r\n  <string>When did y" +
            "ou return from Mumbai?</string>\r\n  <string>When did you meet him last?</string>\r" +
            "\n  <string>When did you join this course?</string>\r\n  <string>When will they com" +
            "e?</string>\r\n  <string>When are you completing the computer course?</string>\r\n  " +
            "<string>Who is he?</string>\r\n  <string>Who is that man standing over there?</str" +
            "ing>\r\n  <string>Who are you?</string>\r\n  <string>Who are you to command me?</str" +
            "ing>\r\n  <string>Who said?</string>\r\n  <string>Who told you?</string>\r\n  <string>" +
            "Who switched off the light?</string>\r\n  <string>Who asked you?</string>\r\n  <stri" +
            "ng>Who called you?</string>\r\n  <string>Who will help you?</string>\r\n  <string>Wh" +
            "o told you that I was not well?</string>\r\n  <string>Whom do you suspect?</string" +
            ">\r\n  <string>With whom did you come?</string>\r\n  <string>Whom did you come with?" +
            "</string>\r\n  <string>Which is your home town?</string>\r\n  <string>Which is your " +
            "bag?</string>\r\n  <string>Which one do you want?</string>\r\n  <string>Which colour" +
            " do you like?</string>\r\n  <string>Which bus goes to Thiruvallur?</string>\r\n  <st" +
            "ring>Which game do you like? Cricket or Tennis.</string>\r\n  <string>Whose book i" +
            "s this?</string>\r\n  <string>Whose mistake is it?</string>\r\n  <string>Whose handw" +
            "riting is this?</string>\r\n  <string>Why is he dull?</string>\r\n  <string>Why is t" +
            "he train late?</string>\r\n  <string>Why are you late?</string>\r\n  <string>Why are" +
            " you laughing?</string>\r\n  <string>Why are you shouting like this?</string>\r\n  <" +
            "string>Why are you getting angry unnecessarily?</string>\r\n  <string>Why are you " +
            "staring at me?</string>\r\n  <string>Why are you asking me?</string>\r\n  <string>Wh" +
            "y are you telling me all this?</string>\r\n  <string>Why do you always wear blue s" +
            "hirts?</string>\r\n  <string>Why do you worry?</string>\r\n  <string>Why did you bea" +
            "t him?</string>\r\n  <string>Why did you resign the job?</string>\r\n  <string>Then," +
            " why did you call me?</string>\r\n  <string>Why did you go there?</string>\r\n  <str" +
            "ing>Then, why did you ask me to come?</string>\r\n  <string>Why did you spend all " +
            "the money?</string>\r\n  <string>Why did you behave like that?</string>\r\n  <string" +
            ">Why didn\'t you apply for the job?</string>\r\n  <string>Why didn\'t you inform me?" +
            "</string>\r\n  <string>Is he binding a book?</string>\r\n  <string>Is he bringing a " +
            "file?</string>\r\n  <string>Is he buying fruits?</string>\r\n  <string>Is he giving " +
            "the book?</string>\r\n  <string>Is he learning English?</string>\r\n  <string>Is he " +
            "paying the fee?</string>\r\n  <string>Is he running?</string>\r\n  <string>Is she ca" +
            "lling you?</string>\r\n  <string>Is she writing a letter?</string>\r\n  <string>Is s" +
            "he cutting a tree?</string>\r\n  <string>Is she reading a novel?</string>\r\n  <stri" +
            "ng>Is she calling your sister?</string>\r\n  <string>Is she going to Delhi?</strin" +
            "g>\r\n  <string>Is the bus corning?</string>\r\n  <string>Is it raining?</string>\r\n " +
            " <string>Is the machine working?</string>\r\n  <string>Is he taking your cell phon" +
            "e?</string>\r\n  <string>Is your mother preparing food?</string>\r\n  <string>Is Chi" +
            "tra calling Priya?</string>\r\n  <string>Is Gayathri waiting for you?</string>\r\n  " +
            "<string>Is Shyamala residing here?</string>\r\n  <string>Is Ravi singing a song?</" +
            "string>\r\n  <string>Is Ashwin giving a lecture?</string>\r\n  <string>Is Maran taki" +
            "ng your pen?</string>\r\n  <string>Is Mala telling a story?</string>\r\n  <string>Is" +
            " he binding a book?</string>\r\n  <string>Is he bringing a file?</string>\r\n  <stri" +
            "ng>Is he buying fruits?</string>\r\n  <string>Is he giving the book?</string>\r\n  <" +
            "string>Is he learning English?</string>\r\n  <string>Is he paying the fee?</string" +
            ">\r\n  <string>Is he running?</string>\r\n  <string>Is she calling you?</string>\r\n  " +
            "<string>Is she writing a letter?</string>\r\n  <string>Is she cutting a tree?</str" +
            "ing>\r\n  <string>Is she reading a novel?</string>\r\n  <string>Is she calling your " +
            "sister?</string>\r\n  <string>Is she going to Delhi?</string>\r\n  <string>Is the bu" +
            "s corning?</string>\r\n  <string>Is it raining?</string>\r\n  <string>Is the machine" +
            " working?</string>\r\n  <string>Is he taking your cell phone?</string>\r\n  <string>" +
            "Is your mother preparing food?</string>\r\n  <string>Is Chitra calling Priya?</str" +
            "ing>\r\n  <string>Is Gayathri waiting for you?</string>\r\n  <string>Is Shyamala res" +
            "iding here?</string>\r\n  <string>Is Ravi singing a song?</string>\r\n  <string>Is A" +
            "shwin giving a lecture?</string>\r\n  <string>Is Maran taking your pen?</string>\r\n" +
            "  <string>Is Mala telling a story?</string>\r\n  <string>Thank you.</string>\r\n  <s" +
            "tring>Thanks a lot.</string>\r\n  <string>Thank you so much.</string>\r\n  <string>T" +
            "hank you very much.</string>\r\n  <string>You have been a great help. Thank you ve" +
            "ry much.</string>\r\n  <string>Thank you very much.</string>\r\n  <string>I will nev" +
            "er forget your timely help.</string>\r\n  <string>It was nice of you to arrange ev" +
            "erything at a short notice.</string>\r\n  <string>I don\'t know how to thank you.</" +
            "string>\r\n  <string>I really don\'t know how to express my thanks to you.</string>" +
            "\r\n  <string>I am very grateful to you.</string>\r\n  <string>I don\'t find words to" +
            " express my thanks to you.</string>\r\n  <string>Thank you for reminding me.</stri" +
            "ng>\r\n  <string>Thanks for calling.</string>\r\n  <string>That\'s OK.</string>\r\n  <s" +
            "tring>That\'s alright.</string>\r\n  <string>No problem.</string>\r\n  <string>Don\'t " +
            "mention it.</string>\r\n  <string>You are welcome.</string>\r\n  <string>Hey..... Ho" +
            "w dare you talk to me like that?</string>\r\n  <string>Were you out of your mind t" +
            "o do such a thing?</string>\r\n  <string>Stop telling me what to do and mind your " +
            "business.</string>\r\n  <string>Are you trying to make a fool of me?</string>\r\n  <" +
            "string>I have come to the end of my patience.</string>\r\n  <string>Don\'t try my p" +
            "atience.</string>\r\n  <string>What the hell do you want?</string>\r\n  <string>You " +
            "are always complaining about something.</string>\r\n  <string>What the devil are y" +
            "ou doing there?</string>\r\n  <string>Do you think you are very smart?</string>\r\n " +
            " <string>Do you think I am not aware of it?</string>\r\n  <string>Behave yourself," +
            " otherwise I will neck you out.</string>\r\n  <string>How are you concerned with m" +
            "y affairs?</string>\r\n  <string>Get out of my sight.</string>\r\n  <string>Go to he" +
            "ll.</string>\r\n  <string>Get lost.</string>\r\n  <string>Don\'t lose your temper.</s" +
            "tring>\r\n  <string>Keep cool.</string>\r\n  <string>Keep yourself cool.</string>\r\n " +
            " <string>Don\'t worry. Everything will go off well.</string>\r\n  <string>There is " +
            "no need to worry.</string>\r\n  <string>Stop worrying. Everything will be alright." +
            "</string>\r\n  <string>It was nobody\'s fault. Why do you worry?</string>\r\n  <strin" +
            "g>Look. There is nothing to get nervous about.</string>\r\n  <string>Everybody mak" +
            "es mistakes sometimes you know.</string>\r\n  <string>Forget it. Anyone can make a" +
            " mistake.</string>\r\n  <string>I am sure it was not your fault and everybody know" +
            "s it.</string>\r\n  <string>Nothing like that will happen again. Don\'t worry.</str" +
            "ing>\r\n  <string>Why fear when I am here?</string>\r\n  <string>Why fear as long as" +
            " I am with you?</string>\r\n  <string>Don\'t worry. I too have the same problem.</s" +
            "tring>\r\n  <string>Tears don\'t solve any problem.</string>\r\n  <string>There is al" +
            "ways a solution to any problem.</string>\r\n  <string>Through thick and thin I wil" +
            "l stand by you.</string>\r\n  <string>Rain or shine, I will stand by you.</string>" +
            "\r\n  <string>Whatever is destined to happen, will happen.</string>\r\n  <string>Lif" +
            "e is not suffering all the time.</string>\r\n  <string>Nothing can be achieved by " +
            "feeling depressed like this.</string>\r\n  <string>What time do you get up in the " +
            "morning?</string>\r\n  <string>I get up at 6.30.</string>\r\n  <string>I get up at 5" +
            ".15.</string>\r\n  <string>What do you have in the morning? Coffee or tea?</string" +
            ">\r\n  <string>Normally, I have tea in the morning.</string>\r\n  <string>Which news" +
            "paper do you read?</string>\r\n  <string>I read the Times.</string>\r\n  <string>I b" +
            "uy the Hindu as well.</string>\r\n  <string>Do you have time to read the paper in " +
            "the morning?</string>\r\n  <string>Yes. I have.</string>\r\n  <string>No. I have a v" +
            "ery busy schedule in the morning.</string>\r\n  <string>I just go through the head" +
            "lines.</string>\r\n  <string>What do you have for your breakfast?</string>\r\n  <str" +
            "ing>Mostly idlis, sometimes dosa or pongal.</string>\r\n  <string>When do you leav" +
            "e for office?</string>\r\n  <string>I leave at 9.15.</string>\r\n  <string>How do yo" +
            "u go to office?</string>\r\n  <string>I go by train.</string>\r\n  <string>I go by b" +
            "us.</string>\r\n  <string>I go by scooter.</string>\r\n  <string>I go by cycle.</str" +
            "ing>\r\n  <string>When do you return home?</string>\r\n  <string>I return home at 6." +
            "30.</string>\r\n  <string>When do you go to bed?</string>\r\n  <string>I go to bed a" +
            "t 10.30.</string>\r\n  <string>Did you type the letter?</string>\r\n  <string>Did he" +
            " come here yesterday?</string>\r\n  <string>Did you lock the door?</string>\r\n  <st" +
            "ring>Did you switch off the T.V.?</string>\r\n  <string>Did you get my letter?</st" +
            "ring>\r\n  <string>Did you receive my letter?</string>\r\n  <string>Did it rain ther" +
            "e?</string>\r\n  <string>Did anybody come?</string>\r\n  <string>Did he say anything" +
            "?</string>\r\n  <string>Did you go to office yesterday?</string>\r\n  <string>Did yo" +
            "u call me?</string>\r\n  <string>Did I give you the balance?</string>\r\n  <string>D" +
            "id I ask you?</string>\r\n  <string>Did you reach there on time?</string>\r\n  <stri" +
            "ng>Did you get there on time?</string>\r\n  <string>Did you return the book?</stri" +
            "ng>\r\n  <string>Did he ask you anything about that?</string>\r\n  <string>Did you u" +
            "nderstand this lesson?</string>\r\n  <string>Did he come?</string>\r\n  <string>When" +
            " did he come?</string>\r\n  <string>Where did he come?</string>\r\n  <string>How did" +
            " he come?</string>\r\n  <string>Why did he come here?</string>\r\n  <string>With who" +
            "m did he come?</string>\r\n  <string>When did he come?</string>\r\n  <string>He came" +
            " here last week.</string>\r\n  <string>He came here yesterday.</string>\r\n  <string" +
            ">Where did he come?</string>\r\n  <string>He came here.</string>\r\n  <string>He cam" +
            "e to my office.</string>\r\n  <string>How did he come?</string>\r\n  <string>He came" +
            " by bus.</string>\r\n  <string>He came by car.</string>\r\n  <string>Why did he come" +
            "?</string>\r\n  <string>He came to meet my father.</string>\r\n  <string>He came to " +
            "my office to ask for money.</string>\r\n  <string>He just made a courtesy visit.</" +
            "string>\r\n  <string>With whom did he come?</string>\r\n  <string>He came along with" +
            " his wife.</string>\r\n  <string>He came here alone.</string>\r\n  <string>Will they" +
            " come here?</string>\r\n  <string>When will they come?</string>\r\n  <string>Are the" +
            "y coming here tomorrow?</string>\r\n  <string>What are you going to do?</string>\r\n" +
            "  <string>When are you completing the work?</string>\r\n  <string>When are you goi" +
            "ng to get married?</string>\r\n  <string>Are you going with them?</string>\r\n  <str" +
            "ing>When are you going to vacate the house?</string>\r\n  <string>How long are you" +
            " going to stay there?</string>\r\n  <string>What are you going to do next?</string" +
            ">\r\n  <string>How will you manage?</string>\r\n  <string>How are you going to manag" +
            "e?</string>\r\n  <string>When is the manager returning from Trichy?</string>\r\n  <s" +
            "tring>Will it rain today?</string>\r\n  <string>When are you leaving for Madurai?<" +
            "/string>\r\n  <string>They are giving the bonus next week.</string>\r\n  <string>I a" +
            "m leaving for Salem tomorrow night.</string>\r\n  <string>They are vacating the ho" +
            "use next month.</string>\r\n  <string>Next week my cousin is coming from Mumbai.</" +
            "string>\r\n  <string>I have to take her to Kumbakonam.</string>\r\n  <string>My frie" +
            "nd Surya is getting married next month.</string>\r\n  <string>I am leaving for Ban" +
            "galore tonight and I will be back after 10 days.</string>\r\n  <string>You just wa" +
            "it there. I will come and pick you up.</string>\r\n  <string>I will take you there" +
            " one day.</string>\r\n  <string>I think it will rain today.</string>\r\n  <string>I " +
            "hope they will win.</string>\r\n  <string>It is already 8.30. I don\'t think they w" +
            "ill come.</string>\r\n  <string>Hereafter I won\'t go with them.</string>\r\n  <strin" +
            "g>They won\'t mistake me.</string>\r\n  <string>Nobody will believe that.</string>\r" +
            "\n  <string>They will not listen to me.</string>\r\n  <string>Where do you keep you" +
            "r books?</string>\r\n  <string>I keep my books here.</string>\r\n  <string>Where do " +
            "you buy your dresses?</string>\r\n  <string>I buy my dresses in T.Nagar.</string>\r" +
            "\n  <string>Where do you wait for him?</string>\r\n  <string>I wait for him at the " +
            "station.</string>\r\n  <string>Where do you look for him?</string>\r\n  <string>We l" +
            "ook for him at the library.</string>\r\n  <string>Where do you have your bank acco" +
            "unt?</string>\r\n  <string>I have my bank account in Trichy.</string>\r\n  <string>W" +
            "here do they want you to come?</string>\r\n  <string>They want me to come to Madur" +
            "ai.</string>\r\n  <string>Where do I ask Sita to wait?</string>\r\n  <string>You ask" +
            " Sita to wait in her office.</string>\r\n  <string>Where do I come from?</string>\r" +
            "\n  <string>You come from Ooty.</string>\r\n  <string>Where do you come from?</stri" +
            "ng>\r\n  <string>We come from Salem.</string>\r\n  <string>Where do they send this p" +
            "arcel to?</string>\r\n  <string>They send this parcel to Kanyakumari.</string>\r\n  " +
            "<string>I like reading books.</string>\r\n  <string>I like getting wet in the rain" +
            ".</string>\r\n  <string>I like walking in the morning sun.</string>\r\n  <string>I l" +
            "ike listening to music.</string>\r\n  <string>I like travelling by train.</string>" +
            "\r\n  <string>I like playing cricket.</string>\r\n  <string>I like watching T.V.</st" +
            "ring>\r\n  <string>I like people who are frank.</string>\r\n  <string>I like people " +
            "who speak the truth.</string>\r\n  <string>I like people who work hard.</string>\r\n" +
            "  <string>I don\'t like travelling by crowded buses.</string>\r\n  <string>I don\'t " +
            "like waiting in queues.</string>\r\n  <string>I don\'t like watching the T.V. seria" +
            "ls.</string>\r\n  <string>I don\'t like sitting idle.</string>\r\n  <string>I don\'t l" +
            "ike your going there.</string>\r\n  <string>I don\'t like your telling lies.</strin" +
            "g>\r\n  <string>I have a scooter.</string>\r\n  <string>I have some books.</string>\r" +
            "\n  <string>We have a Maruthi Car.</string>\r\n  <string>I have Ford Car.</string>\r" +
            "\n  <string>I have two brothers.</string>\r\n  <string>I have three sisters and a b" +
            "rother.</string>\r\n  <string>I have a lot of friends here.</string>\r\n  <string>I " +
            "have office tomorrow.</string>\r\n  <string>I have college today.</string>\r\n  <str" +
            "ing>I have a meeting today.</string>\r\n  <string>We have a function at home tomor" +
            "row.</string>\r\n  <string>We have some guests at home.</string>\r\n  <string>I have" +
            " a car.</string>\r\n  <string>He has a car.</string>\r\n  <string>She has a car.</st" +
            "ring>\r\n  <string>She has two children.</string>\r\n  <string>He has office today.<" +
            "/string>\r\n  <string>Sujatha has school tomorrow.</string>\r\n  <string>He has a fr" +
            "iend in Mumbai.</string>\r\n  <string>I have no time.</string>\r\n  <string>I don\'t " +
            "have time.</string>\r\n  <string>He has no time.</string>\r\n  <string>He doesn\'t ha" +
            "ve time.</string>\r\n  <string>I have no office today.</string>\r\n  <string>They ha" +
            "ve no school tomorrow.</string>\r\n  <string>I have no problem.</string>\r\n  <strin" +
            "g>I have no objection.</string>\r\n  <string>Excuse me. Do you have a spare ticket" +
            "?</string>\r\n  <string>Sir, do you have any extra tickets?</string>\r\n  <string>Ex" +
            "cuse me. Do you have change for Rs.500?</string>\r\n  <string>Do you have a one ru" +
            "pee coin?</string>\r\n  <string>Dad, do you have office tomorrow?</string>\r\n  <str" +
            "ing>Do you have school today?</string>\r\n  <string>Does she have any problem?</st" +
            "ring>\r\n  <string>Do you have a pen?</string>\r\n  <string>Don\'t you have a pen?</s" +
            "tring>\r\n  <string>Don\'t you have school today?</string>\r\n  <string>Don\'t you hav" +
            "e change?</string>\r\n  <string>Do you have any doubt?</string>\r\n  <string>Sir, co" +
            "uld I park my scooter here?</string>\r\n  <string>Could I use your phone?</string>" +
            "\r\n  <string>It is very hot inside. Can I open the windows?</string>\r\n  <string>C" +
            "an I borrow this Look for a day?</string>\r\n  <string>May I have a word with you," +
            " sir?</string>\r\n  <string>Sir, can I go home early today? I have some guests at " +
            "home.</string>\r\n  <string>Can I leave my bag here?</string>\r\n  <string>Yes. You " +
            "can.</string>\r\n  <string>By all means.</string>\r\n  <string>Yes. Certainly.</stri" +
            "ng>\r\n  <string>Oh. Sure!</string>\r\n  <string>No problem.</string>\r\n  <string>I d" +
            "on\'t mind.</string>\r\n  <string>I don\'t mind it at all.</string>\r\n  <string>I am " +
            "sorry.</string>\r\n  <string>Sorry. You can\'t.</string>\r\n  <string>It\'s ok with me" +
            ", but you must ask the M.D.</string>\r\n  <string>Can we go to the practice now?</" +
            "string>\r\n  <string>Ask him to come tomorrow.</string>\r\n  <string>Ask Ramesh to w" +
            "ait for sometime.</string>\r\n  <string>Ask him to bring the book.</string>\r\n  <st" +
            "ring>Ask Ravi to finish the home work.</string>\r\n  <string>Ask Sheela to shut up" +
            ".</string>\r\n  <string>Ask him to bring his father tomorrow.</string>\r\n  <string>" +
            "Ask Sekar to go to the bank.</string>\r\n  <string>Ask him to bring the files.</st" +
            "ring>\r\n  <string>Ask him to wait till I come.</string>\r\n  <string>Ask your frien" +
            "d Surya to meet me tomorrow.</string>\r\n  <string>Ask him not to go there.</strin" +
            "g>\r\n  <string>Ask them not to wait for me.</string>\r\n  <string>Ask that man not " +
            "to shout.</string>\r\n  <string>Ask the children not to get wet in the rain.</stri" +
            "ng>\r\n  <string>Ask my mother not to worry about me.</string>\r\n  <string>I didn\'t" +
            " ask you to go there.</string>\r\n  <string>I didn\'t ask them to come here.</strin" +
            "g>\r\n  <string>I don\'t know why they have come.</string>\r\n  <string>I didn\'t ask " +
            "you to spend all the money.</string>\r\n  <string>I didn’t ask you to wait for me." +
            "</string>\r\n  <string>Did I ask you to go there?</string>\r\n  <string>Did I ask yo" +
            "u to resign the job?</string>\r\n  <string>Did I ask you to keep the door open?</s" +
            "tring>\r\n  <string>Did I ask them to wait?</string>\r\n  <string>I asked you to com" +
            "e yesterday, but you didn\'t come.</string>\r\n  <string>I asked you not to go ther" +
            "e. Did you listen to me?</string>\r\n  <string>I asked you several times not to be" +
            "lieve them, but you didn\'t listen to me.</string>\r\n  <string>I have asked you se" +
            "veral times not to keep anything on the T.V., but you never listen to me.</strin" +
            "g>\r\n  <string>Have I ever asked you to work on Sundays?</string>\r\n  <string>Wait" +
            " for sometime.</string>\r\n  <string>My friend Ravi has a scooter.</string>\r\n  <st" +
            "ring>I will ask him to drop you.</string>\r\n  <string>I will ask them to wait.</s" +
            "tring>\r\n  <string>I will ask him to meet you tomorrow at 5 o\'clock.</string>\r\n  " +
            "<string>I will ask him to call you up</string>\r\n  <string>I will ask her to cook" +
            " today.</string>\r\n  <string>I will ask him to get you something to eat.</string>" +
            "\r\n  <string>I will ask Ramesh to reserve two tickets.</string>\r\n  <string>Shall " +
            "I ask them to come tomorrow?</string>\r\n  <string>Shall I ask him to call you up?" +
            "</string>\r\n  <string>Shall I ask them to wait?</string>\r\n  <string>Sir. Mr. Siva" +
            " is on leave today.</string>\r\n  <string>Shall I ask Mr. Hari to go to the bank?<" +
            "/string>\r\n  <string>Shall I ask Sheela to send the email?</string>\r\n  <string>Sh" +
            "all I ask Mrs. Geetha to use the CD instead of floppy?</string>\r\n  <string>Does " +
            "he act well?</string>\r\n  <string>Does he add wealth?</string>\r\n  <string>Did she" +
            " ask me?</string>\r\n  <string>Do I adopt a child?</string>\r\n  <string>Is computer" +
            " an advanced Technology?</string>\r\n  <string>Does he advantage a lot?</string>\r\n" +
            "  <string>Do they advertise a lot?</string>\r\n  <string>Does the govt. allot hous" +
            "es?</string>\r\n  <string>Did the H.M announce the holiday?</string>\r\n  <string>Di" +
            "d she appeal?</string>\r\n  <string>Does the sun appear?</string>\r\n  <string>Was I" +
            " appointed?</string>\r\n  <string>Does he approve the idea?</string>\r\n  <string>Do" +
            "es the boy arise?</string>\r\n  <string>Did he arrange a function?</string>\r\n  <st" +
            "ring>Did the police arrest him?</string>\r\n  <string>Did he attempt?</string>\r\n  " +
            "<string>Does he attend the function?</string>\r\n  <string>Do you avoid me?</strin" +
            "g>\r\n  <string>Did I get clarity in my doubt?</string>\r\n  <string>Did he combine " +
            "the sentences?</string>\r\n  <string>Will you meet me?</string>\r\n  <string>Does he" +
            " complain?</string>\r\n  <string>Did he award him?</string>\r\n  <string>Did I barga" +
            "in with the Vendor?</string>\r\n  <string>Does the dog bark?</string>\r\n  <string>D" +
            "oes he bathe in hot water?</string>\r\n  <string>Does he beat me?</string>\r\n  <str" +
            "ing>Does he befit always?</string>\r\n  <string>Does she behold me?</string>\r\n  <s" +
            "tring>Does she bind the grains?</string>\r\n  <string>Does the dog bite?</string>\r" +
            "\n  <string>Does the bomb blast?</string>\r\n  <string>Does the water boil?</string" +
            ">\r\n  <string>Did he borrow a pen?</string>\r\n  <string>Did he servant bow?</strin" +
            "g>\r\n  <string>Does the enemy bowl him?</string>\r\n  <string>If you had called me," +
            " I would have come there.</string>\r\n  <string>If you had told me, I would have w" +
            "aited for you.</string>\r\n  <string>If he had asked me, I would have given it to " +
            "him.</string>\r\n  <string>If I had been awake, I would have caught the thief.</st" +
            "ring>\r\n  <string>They came all the way to invite you.</string>\r\n  <string>You sh" +
            "ould have attended the wedding.</string>\r\n  <string>You should have told me yest" +
            "erday.</string>\r\n  <string>You should have replied to his letter.</string>\r\n  <s" +
            "tring>I should have joined this course last year.</string>\r\n  <string>Whatever i" +
            "t may be, you should not have beaten him.</string>\r\n  <string>I should not have " +
            "wasted my time.</string>\r\n  <string>You should not have talked like that.</strin" +
            "g>\r\n  <string>It was my mistake.</string>\r\n  <string>I should not have invited t" +
            "hem to the party.</string>\r\n  <string>You could have come by auto.</string>\r\n  <" +
            "string>I could have come by auto, but who would pay the fare?</string>\r\n  <strin" +
            "g />\r\n  <string>On which platform is the Brindavan Express?</string>\r\n  <string>" +
            "What time does the Brindavan Express leave?</string>\r\n  <string>Has the Brindava" +
            "n left?</string>\r\n  <string>Has the Brindavan arrived?</string>\r\n  <string>Will " +
            "the train halt at Arakkonam?</string>\r\n  <string>When does the train reach Banga" +
            "lore?</string>\r\n  <string>Why is the train delayed?</string>\r\n  <string>Where is" +
            " the ticket counter?</string>\r\n  <string>Where is the reservation counter?</stri" +
            "ng>\r\n  <string>Is reservation available for 16th on Brindavan?</string>\r\n  <stri" +
            "ng>What is the waiting list number?</string>\r\n  <string>Could you allot a seat n" +
            "ear the window?</string>\r\n  <string>Can I get the return ticket here?</string>\r\n" +
            "  <string>Sir, how much would I lose if I cancelled the ticket?</string>\r\n  <str" +
            "ing>It is very cold.</string>\r\n  <string>Would you mind closing the window?</str" +
            "ing>\r\n  <string>Sir, have we crossed Jolarpet?</string>\r\n  <string>Sir, I am to " +
            "get down at Ambur.</string>\r\n  <string>Could you wake me up if you are awake?</s" +
            "tring>\r\n  <string>Sir, it\'s midnight. Please switch off the light. I feel sleepy" +
            ".</string>\r\n  <string>When is the next flight to Delhi?</string>\r\n  <string>Is t" +
            "here a Jet Airways Flight to Delhi?</string>\r\n  <string>When does it land at Mum" +
            "bai?</string>\r\n  <string>When is the Sahara Flight from Delhi expected?</string>" +
            "\r\n  <string>Sir, I must be in Delhi this evening to attend an important meeting." +
            "</string>\r\n  <string>If I miss it, I stand to a great loss. Please help me out s" +
            "ir.</string>\r\n  <string>Sir, I have to be in Delhi by this evening before 5.30.<" +
            "/string>\r\n  <string>I need your help in this regard.</string>\r\n  <string>Where i" +
            "s the immigration check counter?</string>\r\n  <string>May I take the passport ple" +
            "ase?</string>\r\n  <string>How much US dollars (or British Pounds) will I get?</st" +
            "ring>\r\n  <string>Where to check-in for Indian Airlines flight to Delhi?</string>" +
            "\r\n  <string>I\'ll handover some of my stuff to my friend. I\'ll be back.</string>\r" +
            "\n  <string>Where do I collect my baggage?</string>\r\n  <string>Where to ask for p" +
            "repaid taxi?</string>\r\n  <string>Can I keep this with me as hand baggage?</strin" +
            "g>\r\n  <string>Which bus goes to Gandhi Nagar?</string>\r\n  <string>Does this bus " +
            "go to Gandhi Nagar?</string>\r\n  <string>What all buses go to Gandhi Nagar?</stri" +
            "ng>\r\n  <string>Is the bus that just left Gandhi Nagar bus?</string>\r\n  <string>W" +
            "hen is the next bus to Gandhi Nagar?</string>\r\n  <string>Which bus has just left" +
            "?</string>\r\n  <string>Does this bus go via Ashok Nagar?</string>\r\n  <string>Sir," +
            " I am to get down at Gandhi Nagar.</string>\r\n  <string>Would you mind telling me" +
            " when we get there? I am new to this town.</string>\r\n  <string>Sir, would you mi" +
            "nd keeping this bag under the seat?</string>\r\n  <string>Sir, please get me a tic" +
            "ket to Gandhi Nagar.</string>\r\n  <string>Sir, would you mind moving a bit.</stri" +
            "ng>\r\n  <string>It is very congested here.</string>\r\n  <string>Conductor, you hav" +
            "en\'t paid the balance. I am to get down at the next stop.</string>\r\n  <string>Wh" +
            "ere can I get the application form for opening SB account?</string>\r\n  <string>C" +
            "an I have an application form for SB Account please?</string>\r\n  <string>Whom sh" +
            "ould I meet to open the account?</string>\r\n  <string>Is introduction a must?</st" +
            "ring>\r\n  <string>Sir, I am new to this town. I am working in Kaveri chemicals. T" +
            "his is my identity card. Will this card do to open the account?</string>\r\n  <str" +
            "ing>How many photos are needed?</string>\r\n  <string>What is the minimum amount t" +
            "o be deposited to open an account?</string>\r\n  <string>What is the minimum balan" +
            "ce I should keep to have cheque book facility?</string>\r\n  <string>Where can I c" +
            "ollect the pass book?</string>\r\n  <string>Do you have ATM facility?</string>\r\n  " +
            "<string>What are your working hours?</string>\r\n  <string>Do you work on Sundays?" +
            "</string>\r\n  <string>Last week I deposited a cheque. Has the amount been credite" +
            "d to my account?</string>\r\n  <string>Is it US Bank?</string>\r\n  <string>Is it S." +
            "M. Travels?</string>\r\n  <string>Is it Prasad\'s residence?</string>\r\n  <string>Is" +
            " it John’s residence?</string>\r\n  <string>Can I speak to Mr. Suresh, please?</st" +
            "ring>\r\n  <string>Could I speak to Mr. Suresh please?</string>\r\n  <string>Can I s" +
            "peak to Mr. Obama?</string>\r\n  <string>Could I speak to Mr. Johnson?</string>\r\n " +
            " <string>Please connect me to Extension 2434.</string>\r\n  <string>Please put me " +
            "to Extension 2434.</string>\r\n  <string>May I know who is speaking?</string>\r\n  <" +
            "string>May I know who is calling?</string>\r\n  <string>I am Ravi calling from Mad" +
            "urai.</string>\r\n  <string>I am Clinton calling from London.</string>\r\n  <string>" +
            "I am Adjani calling from Mumbai.</string>\r\n  <string>I am Kala calling from Moth" +
            "er Computer Graphics.</string>\r\n  <string>I am Kala from Mother Computer Graphic" +
            "s.</string>\r\n  <string>Can I speak to Mr. Suresh please?</string>\r\n  <string>Yes" +
            ", speaking.</string>\r\n  <string>Just a minute please.</string>\r\n  <string>Just a" +
            " moment please.</string>\r\n  <string>Please hold on.</string>\r\n  <string>Would yo" +
            "u please hold on?</string>\r\n  <string>Sir, there is a call for you.</string>\r\n  " +
            "<string>Sir, Mr. Ravi is on the line.</string>\r\n  <string>Sir, he is speaking ov" +
            "er the other line.</string>\r\n  <string>He is on the other line.</string>\r\n  <str" +
            "ing>Sir, he is out of town and he will be back only next week.</string>\r\n  <stri" +
            "ng>He is on leave.</string>\r\n  <string>He has gone out.</string>\r\n  <string>Sir," +
            " he has gone home for lunch.</string>\r\n  <string>When is he expected?</string>\r\n" +
            "  <string>When will he be back?</string>\r\n  <string>He is out of town.</string>\r" +
            "\n  <string>When is he returning?</string>\r\n  <string>He is on leave.</string>\r\n " +
            " <string>When is he reporting for duty?</string>\r\n  <string>Just a minute please" +
            ". I\'ll find out whether he is available.</string>\r\n  <string>Can I speak to Mr. " +
            "Sultan?</string>\r\n  <string>Sir, nobody is here by that name.</string>\r\n  <strin" +
            "g>Sir, nobody by that name here. </string>\r\n  <string>Any message please?</strin" +
            "g>\r\n  <string>Can I take any message?</string>\r\n  <string>Anything to convey?</s" +
            "tring>\r\n  <string>Would you like to leave any message?</string>\r\n  <string>Shall" +
            " I ask him to call you back?</string>\r\n  <string>Shall I ask him to contact you?" +
            "</string>\r\n  <string>Please tell him that Suresh called.</string>\r\n  <string>Ask" +
            " him to call me as soon as he returns.</string>\r\n  <string>He is not available. " +
            "Would you like to speak to his assistant?</string>\r\n  <string>He is not availabl" +
            "e. I\'ll be glad to help you.</string>\r\n  <string>Please ask him to call my resid" +
            "ence.</string>\r\n  <string>He knows my number.</string>\r\n  <string>Ask him to cal" +
            "l me. He has my number.</string>\r\n  <string>Your number please.</string>\r\n  <str" +
            "ing>Can I have your number please?</string>\r\n  <string>May I know your number pl" +
            "ease?</string>\r\n  <string>I am Saravanan calling from Singapore. Would you pleas" +
            "e call Mr. Raja your neighbour?</string>\r\n  <string>Excuse me madam, May I come " +
            "in?</string>\r\n  <string>Please do.</string>\r\n  <string>I am Mrs. Radha. I have c" +
            "ome here regarding my son Mahesh\'s admission in your school.</string>\r\n  <string" +
            ">I am Mrs. Clinton.</string>\r\n  <string>I would like to admit my son John in you" +
            "r school.</string>\r\n  <string>I would like to admit my daughter Mary in your sch" +
            "ool.</string>\r\n  <string>You want to admit your son in which standard?</string>\r" +
            "\n  <string>I want to admit him in sixth standard.</string>\r\n  <string>How old is" +
            " your son?</string>\r\n  <string>He is 10 years old.</string>\r\n  <string>Where did" +
            " he study earlier?</string>\r\n  <string>He studied in Bharathiar School, Chennai." +
            "</string>\r\n  <string>He studied in St. Andrew’s School.</string>\r\n  <string>Why " +
            "is he leaving that school?</string>\r\n  <string>His father has been transferred t" +
            "o this/place.</string>\r\n  <string>Have you taken a TC from the old school?</stri" +
            "ng>\r\n  <string>Of course Madam I have it here.</string>\r\n  <string>Does the scho" +
            "ol work this Saturday?</string>\r\n  <string>Could I meet the class teacher?</stri" +
            "ng>\r\n  <string>I would like to meet the class teacher.</string>\r\n  <string>I got" +
            " a letter from the H.M. asking me to meet him.</string>\r\n  <string>I am Mrs. Rad" +
            "ha, mother of Suresh.</string>\r\n  <string>How is Suresh studying?</string>\r\n  <s" +
            "tring>I have come to enquire about my son\'s performance in the class. How is he " +
            "doing?</string>\r\n  <string>When will the school be over today?</string>\r\n  <stri" +
            "ng>When does the vacation start?</string>\r\n  <string>How has he done at the exam" +
            "s?</string>\r\n  <string>How has he performed in the exams?</string>\r\n  <string>Wh" +
            "en do you reopen the school?</string>\r\n  <string>Have you announced the entrance" +
            " test results?</string>\r\n  <string>When is the last day for paying the fees?</st" +
            "ring>\r\n  <string>When is the sports day?</string>\r\n  <string>Where is it going t" +
            "o be held?</string>\r\n  <string>Do you have a school bus?</string>\r\n  <string>Is " +
            "he coming regularly?</string>\r\n  <string>Is he regular to the classes?</string>\r" +
            "\n  <string>What are your working hours?</string>\r\n  <string>When is your weekly " +
            "off?</string>\r\n  <string>Does Mr. Pandian coming from K.K. Nagar work here?</str" +
            "ing>\r\n  <string>Is Mr. Sadhasivam still working here?</string>\r\n  <string>What i" +
            "s your manager\'s name?</string>\r\n  <string>Where is his residence?</string>\r\n  <" +
            "string>Where is your godown?</string>\r\n  <string>Where is your warehouse?</strin" +
            "g>\r\n  <string>Sir, I am a paper supplier. It seems you wanted some papers. Whom " +
            "should I meet in this connection?</string>\r\n  <string>Do you have your branch in" +
            " Erode?</string>\r\n  <string>Who are your bankers?</string>\r\n  <string>How long i" +
            "s he on leave?</string>\r\n  <string>Sir, I am Ramesh Kumar from Alpha Agencies. W" +
            "e were informed that our cheque is ready. Whom should I meet to collect the cheq" +
            "ue?</string>\r\n  <string>Who does your printing job?</string>\r\n  <string>How is y" +
            "our manager? Is he a Keralite?</string>\r\n  <string>In which department is Latha " +
            "working?</string>\r\n  <string>How many people work here?</string>\r\n  <string>Is y" +
            "our office fully computerised?</string>\r\n  <string>Doctor, I have a severe heada" +
            "che.</string>\r\n  <string>I have a bad cold.</string>\r\n  <string>I have a sense o" +
            "f giddiness.</string>\r\n  <string>I have a dull feeling.</string>\r\n  <string>Ther" +
            "e is a numb feeling in the leg.</string>\r\n  <string>I feel feverish.</string>\r\n " +
            " <string>I have a burning sensation in the eyes.</string>\r\n  <string>I have a bi" +
            "tter taste in the mouth.</string>\r\n  <string>I have mouth sores.</string>\r\n  <st" +
            "ring>I don\'t have a good appetite.</string>\r\n  <string>I have a very bad earache" +
            ".</string>\r\n  <string>My throat is a bit dry.</string>\r\n  <string>Doctor, my wei" +
            "ght has picked up again.</string>\r\n  <string>Should I take these tablets before " +
            "the meal or after the meal?</string>\r\n  <string>How long should I take this medi" +
            "cine?</string>\r\n  <string>Doctor, what is the problem with me?</string>\r\n  <stri" +
            "ng>What exactly is the disease?</string>\r\n  <string>Is it serious?</string>\r\n  <" +
            "string>What should be my diet?</string>\r\n  <string>How long should I take rest?<" +
            "/string>\r\n  <string>Can I take rice and curd?</string>\r\n  <string>Can I travel?<" +
            "/string>\r\n  <string>When can I get the medical report?</string>\r\n  <string>When " +
            "can I collect the X-ray?</string>\r\n  <string>Can I go to work next week?</string" +
            ">\r\n  <string>How much should I pay?</string>\r\n  <string>What is your name?</stri" +
            "ng>\r\n  <string>What is your father?</string>\r\n  <string>Which is your home town?" +
            "</string>\r\n  <string>Could you tell us something about yourself?</string>\r\n  <st" +
            "ring>I am a graduate in commerce.</string>\r\n  <string>I am a B.Com., graduate.</" +
            "string>\r\n  <string>I am a B.Sc., graduate.</string>\r\n  <string>I have done my B." +
            "Sc.,</string>\r\n  <string>Sir, I am basically a commerce graduate and I have comp" +
            "leted my advanced diploma in computers.</string>\r\n  <string>Sir, I am a commerce" +
            " graduate with a diploma in computer applications.</string>\r\n  <string>Sir, I ha" +
            "ve done my B.Com. and now I am doing my computer course.</string>\r\n  <string>Hav" +
            "e you any previous experience?</string>\r\n  <string>Sir, I have three years of ex" +
            "perience in computer accounting.</string>\r\n  <string>Sir I have five years of ex" +
            "perience in Editing.</string>\r\n  <string>I have put in three years of service in" +
            " Film Making.</string>\r\n  <string>I am afraid, I have no experience.</string>\r\n " +
            " <string>You have no experience at all. How do you expect us to give you the job" +
            "?</string>\r\n  <string>Sir, I agree with you I have no experience. But I am a fas" +
            "t learner sir.</string>\r\n  <string>I pickup very fast. I become experienced in j" +
            "ust a very short period.</string>\r\n  <string>I would like to buy a doll within U" +
            "SD $ 20.</string>\r\n  <string>I am looking for a gift, may be a doll within USD $" +
            " 20.</string>\r\n  <string>Can you suggest a nice gift for a two year old female c" +
            "hild?</string>\r\n  <string>How much does it cost?</string>\r\n  <string>How much is" +
            " it?</string>\r\n  <string>Do you have metal chiffon saree?</string>\r\n  <string>Ha" +
            "ve you got designer saree?</string>\r\n  <string>What is the difference between th" +
            "ese two?</string>\r\n  <string>Where can I collect the material?</string>\r\n  <stri" +
            "ng>Can I return the chudidhar if it doesn\'t fit?</string>\r\n  <string>Don\'t you h" +
            "ave it in shades of blue?</string>\r\n  <string>I bought this shirt yesterday.</st" +
            "ring>\r\n  <string>Here is the bill.</string>\r\n  <string>Can I have a replacement?" +
            "</string>\r\n  <string>Is there nobody here at this counter? I have been waiting f" +
            "or half an hour.</string>\r\n  <string>I would like to meet the manager. I have a " +
            "complaint to make.</string>\r\n  <string>Please pack it up neatly.</string>\r\n  <st" +
            "ring>Sorry I am late. I missed the bus.</string>\r\n  <string>I apologise. It was " +
            "my mistake.</string>\r\n  <string>I apologise for talking to you like that.</strin" +
            "g>\r\n  <string>I am afraid, I can\'t come on Sunday.</string>\r\n  <string>I am sorr" +
            "y it is wrong number.</string>\r\n  <string>I am sorry I am late.</string>\r\n  <str" +
            "ing>It\'s okay.</string>\r\n  <string>I could not return the book yesterday. I am s" +
            "o sorry.</string>\r\n  <string>It doesn\'t matter, but don\'t make it a habit.</stri" +
            "ng>\r\n  <string>I am sorry. I forgot to post the letter.</string>\r\n  <string>No p" +
            "roblem. You can post it tomorrow.</string>\r\n  <string>I am sorry. I have broken " +
            "the cup.</string>\r\n  <string>That is okay. It sometimes happens like that.</stri" +
            "ng>\r\n  <string>I am sorry. I have disturbed you.</string>\r\n  <string>No, not at " +
            "all.</string>\r\n  <string>I am terribly sorry. This is all entirely my fault.</st" +
            "ring>\r\n  <string>Okay, it doesn\'t matter, but don\'t let it happen again.</string" +
            ">\r\n  <string>Can you complete the work in two days?</string>\r\n  <string>I may go" +
            " to Delhi tomorrow.</string>\r\n  <string>It might rain today.</string>\r\n  <string" +
            ">You had better consult your father.</string>\r\n  <string>You had better carry so" +
            "mething with you to eat.</string>\r\n  <string>You may feel hungry on the way.</st" +
            "ring>\r\n  <string>You should rather have milk than coffee.</string>\r\n  <string>I " +
            "would rather go hungry than eat this food.</string>\r\n  <string>I must return thi" +
            "s book today.</string>\r\n  <string>You must not come in with your shoes on.</stri" +
            "ng>\r\n  <string>He has to appear for an entrance test.</string>\r\n  <string>You sh" +
            "ould read a lot.</string>\r\n  <string>You should take care of your health.</strin" +
            "g>\r\n  <string>You ought to wear a helmet while travelling.</string>\r\n  <string>T" +
            "he police ought to control the traffic.</string>\r\n  <string>You are supposed to " +
            "complete the work by this evening.</string>\r\n  <string>Why don\'t you do some com" +
            "puter course?</string>\r\n  <string>Can you learn to speak English just in 60 days" +
            "?</string>\r\n  <string>Why not with the help of this site?</string>\r\n  <string>Do" +
            " you have a computer at home?</string>\r\n  <string>Do you have internet connectio" +
            "n?</string>\r\n  <string>Can I have your e-mail Id?</string>\r\n  <string>How freque" +
            "ntly do you check your mail?</string>\r\n  <string>Have you received my e-mail?</s" +
            "tring>\r\n  <string>My floppy drive is not working properly and at times my comput" +
            "er keeps freezing up.</string>\r\n  <string>Do you know any hardware engineer?</st" +
            "ring>\r\n  <string>I think a virus has infected our computer.</string>\r\n  <string>" +
            "Are you familiar with DTP and Multimedia?</string>\r\n  <string>Is there any brows" +
            "ing centre close by?</string>\r\n  <string>Come to the chat room on Sunday at 3. I" +
            "\'ll be online.</string>\r\n  <string>Can you write it on a CD for me?</string>\r\n  " +
            "<string>Is it a copy righted CD?</string>\r\n  <string>Do I require installation f" +
            "or opening the CD?</string>\r\n  <string>On what format have you sent the file?</s" +
            "tring>\r\n  <string>Visit this site if you want more information.</string>\r\n  <str" +
            "ing>Please visit our site.</string>\r\n  <string>You are welcome to visit our site" +
            ".</string>\r\n  <string>Please come.</string>\r\n  <string>Nice of you to make it.</" +
            "string>\r\n  <string>Very nice to have you here.</string>\r\n  <string>I am glad tha" +
            "t you have come.</string>\r\n  <string>I am pleased to have you here.</string>\r\n  " +
            "<string>Please be seated.</string>\r\n  <string>Please have your seat.</string>\r\n " +
            " <string>Make yourself comfortable.</string>\r\n  <string>Would you like something" +
            " to drink?</string>\r\n  <string>Shall we adjourn for dinner?</string>\r\n  <string>" +
            "Shall we start?</string>\r\n  <string>I think it is time for dinner, shall we?</st" +
            "ring>\r\n  <string>Please help yourself.</string>\r\n  <string>Please try this dish." +
            "</string>\r\n  <string>It is quite tasty.</string>\r\n  <string>Would you like secon" +
            "d serving?</string>\r\n  <string>You seem to be a poor eater, why so?</string>\r\n  " +
            "<string>Thank you for attending the party.</string>\r\n  <string>It was a nice eve" +
            "ning.</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Dict {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Dict"]));
            }
            set {
                this["Dict"] = value;
            }
        }
    }
}
